### PR TITLE
Changing RSpec assertions from .should() to the newer, prefered expect().to()

### PR DESCRIPTION
**Pull request by nodanaonlyzuul**
Hullo!

I saw https://github.com/projecthydra/om/issues/48 and figured I'd take a pass at changing the test suite
away from `object.should()` to the newer, preferred `expect(_object_).to(_matcher_)`.

Also - this is my first contribution so I've filed my iCLA this morning and tried my best to adhere to your [guidelines for contributing](https://github.com/projecthydra/om/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jcoyne** [comment]
@nodanaonlyzuul Thanks for your contribution. Does your current employer have a cCLA on file with us as well/

**Comment by nodanaonlyzuul** [comment]
Hey @jcoyne .... hmmm I'm not sure. Although I just began working at NYPL, I haven't signed anything regarding "rights to inventions" or contributing to existing, open source projects - so I'm not sure what the he best way  is to get this PR in with due diligence.

Looking for guidance. Thanks for the fast reply too!

**Comment by jcoyne** [comment]
@nodanaonlyzuul looking into this. We'll be in touch soon.

**Comment by tomcramer** [comment]
@nodanaonlyzuul can you advise who to contact at NYPL about getting a CCLA? We can also take an email cc:'ed to your manager that your contributions under the iCLA are cool with NYPL, per our IP process: https://wiki.duraspace.org/display/hydra/Hydra+Project+Intellectual+Property+Licensing+and+Ownership

**Comment by nodanaonlyzuul** [comment]
I'm going to start a thread CCing my manager.
But I'm also going to find out who the right person is to give clearance for the cCLA...in case team mates contribute to projects in the future.

**Comment by nodanaonlyzuul** [comment]
Thanks for the heads up - I sent an email to my hydra legal, CCing my manager.

In the meantime, for what it's worth, the work in this PR was done on my personal time and equipment, not as an agent of my employer. It doesn't contain any code or patterns extracted from my employer's property. 

That said - it's low a low priority ticket and it would be great to get CLAs in order for future contributions so I leave it to your digression if you want to pull this now or wait.

**Comment by nodanaonlyzuul** [comment]
Just checking in...today, my manager has sent emailed hydra legal explicitly blessing my contribution under iCLA.

**Comment by mjgiarlo** [comment]
Hi @nodanaonlyzuul 

We'll take a look at that shortly and get back to you.  Thanks!

**Comment by nodanaonlyzuul** [comment]
Just a gentle checkin about this PR.
Thanks!

**Comment by mjgiarlo** [comment]
@nodanaonlyzuul Working on this right now.

**Comment by mjgiarlo** [comment]
@nodanaonlyzuul I have your email on file and your supervisor's response, but what I don't seem to have is a signed iCLA: https://wiki.duraspace.org/download/attachments/31662457/Hydra%20Project%20Contributor%20License%20Agreement%20for%20Individuals-20121216.pdf?version=1&modificationDate=1355704453858&api=v2

Did you send that too, or did I just miss it?

**Comment by nodanaonlyzuul** [comment]
Thanks @mjgiarlo. I emailed it to legal@projecthydra.org it Jan 21. 
The subject of the email is "iCLA" (pretty creative :clap:).
I'll re-forward it right now.

**Comment by mjgiarlo** [comment]
Much obliged, sir!

**Comment by mjgiarlo** [comment]
I just searched the email archives for that address and I don't see a message on January 21st.  I wonder if there's some Google Groups spam hijinks afoot here.  I also haven't seen a resend.  Send it directly to michael@psu.edu if you don't mind and I will make sure it makes its way to the right place?

**Comment by nodanaonlyzuul** [comment]
Sent!

**Comment by mjgiarlo** [comment]
Your CLA has been processed and you are now cleared to contribute to Hydra.  Thanks again for your patience and your contribution!

**Comment by nodanaonlyzuul** [comment]
Thanks for rocking this @mjgiarlo and @jcoyne

**Pull request merged**
